# Generated by Django 4.0.1 on 2022-01-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_brand_year_formed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.brand'),
        ),
    ]
